name          'puppet-diamond'
version       '0.2.0'
author        'miguno'
license       'Apache License, Version 2.0'
summary       'Module to manage the Diamond stats collection tool (based on module by garethr)'
project_page  'https://github.com/miguno/puppet-diamond'
dependency    'puppetlabs/stdlib', '>= 4.1.0'
