name         'puppet-diamond'
version      '1.0.2'
author       'miguno'
license      'Apache License, Version 2.0'
summary      'Module to manage the Diamond stats collection tool'
description  'Module to manage the Diamond stats collection tool (based on module by garethr and otherinbox)'
project_page 'https://github.com/miguno/puppet-diamond'
source       'https://github.com/miguno/puppet-diamond'
#DISABLED SO WE DO NOT DEPEND ON PUPPETFORGE#dependency   'puppetlabs/stdlib', '>= 4.1.0'
